In [1]:
import numpy as np

In [2]:

array=np.array([[1,2,3,4],[3,4,5,6],[4,5,6,7]])
array

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [4]:
array2=np.arange(2,8)
array2

array([2, 3, 4, 5, 6, 7])

In [ ]:
#this willgive you the maximum value of array
# we will do this in 1-d and in matrice
np.max(array)


np.int64(7)

In [8]:
np.max(array2)

np.int64(7)

In [9]:
#this will give you mimnimum
np.min(array)

np.int64(1)

In [10]:
# we will get the sum of all the elements of matrices
np.sum(array)

np.int64(50)

In [11]:
np.sum(array2)

np.int64(27)

In [13]:
#now if we have to perfom the sum in rows or in column of matrices then we will use the AXIS 
np.sum(array,axis=0)

array([ 8, 11, 14, 17])

In [14]:
# vertically sum 
np.sum(array,axis=1)

array([10, 18, 22])

In [ ]:
# basics means std and median
np.mean(array2)
np.std(array2)


np.float64(1.707825127659933)

In [20]:
#now reshaping our 1_d into matice
arr3=np.arange(1,11)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr3.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])