In [1]:
import numpy as np

In [4]:
#creation of 1-dimensional array
array=np.arange(1,56)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55])

In [6]:
#we can generate the zeroes and ones
arr=np.zeros(11)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
arr2=np.ones(21)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])

In [13]:
#creation of matrices
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr4=np.ones((2,5))
arr4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
#evenly space number will be provided
arr5=np.linspace(1,5,3)
arr5

array([1., 3., 5.])

In [20]:
arr6=np.linspace(1,10,5)
arr6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
# It allow to generate the random number( concept of normaization)
arr7=np.random.rand(2)
arr7

array([0.90847409, 0.2149903 ])

In [24]:
# it allow the random numner between 3 to -3 ( standarization)
arr7=np.random.randn(4)
arr7

array([ 2.07592283,  1.66963575, -0.23122215,  0.40967718])