In [1]:
import numpy as np

In [3]:
array=np.arange(1,9)
array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
#indexing of array
array[1]

np.int64(2)

In [6]:
#now we are seeing how we can slice or index matrice
array2=np.arange(1,21).reshape(5,4)
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
#indexing of columns is easy
array2[2]

array([ 9, 10, 11, 12])

In [8]:
#if we have to slice the elements between the matrice
array2[2,3]

np.int64(12)

In [12]:
#if we have to find the elements like 14 15 16 18 19 20 so
array2[3:,1:]

array([[14, 15, 16],
       [18, 19, 20]])

In [14]:
# if we have to find rows
array2[0:,:0]

array([], shape=(5, 0), dtype=int64)