In [1]:
import numpy as np

In [ ]:
# arithematic opeartion on array 1st sum
array=np.array([1,2,3,4])
array2=np.array([1,2,3,4])
array+array2

array([2, 4, 6, 8])

In [4]:
# subtract
array-array2

array([0, 0, 0, 0])

In [5]:
#multiply
array*array2

array([ 1,  4,  9, 16])

In [6]:
#divide
array/array2

array([1., 1., 1., 1.])

In [8]:
#modulus
array//array2

array([1, 1, 1, 1])

In [9]:
#power type
array**array2

array([  1,   4,  27, 256])

In [10]:
# broadcasting
array+10

array([11, 12, 13, 14])

In [11]:
array2*2

array([2, 4, 6, 8])

In [13]:
#deep copy and shallow copy

array3=np.array([2,3,4,5,6])
array3[2:5]*10

array([40, 50, 60])

In [14]:
array3

array([2, 3, 4, 5, 6])

In [16]:
#matrice opeartions
array4=np.arange(1,31).reshape(5,6)
array4

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [17]:
array5=np.arange(1,31).reshape(5,6)
array5

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [21]:
#vstack and htack
a=np.array([1,2,3])
b=np.array([3,4,5])
np.vstack((a,b))
np.hstack((a,b))

array([1, 2, 3, 3, 4, 5])