In [1]:
import numpy as np


In [4]:
#creation of numpy array
array1=[1,2,3,4,5,6]
arr=np.array(array1)
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
#conversion of list into array
list1=["harsh",1,2,3,"vansh"]
arr2=np.array(list1)
arr2

array(['harsh', '1', '2', '3', 'vansh'], dtype='<U21')

In [ ]:
# vector form of array array
d=[[1,2,3,4,5],[2,4,5,6,7],[3,4,5,6,7]]
d2=np.array(d)
d2

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 6, 7],
       [3, 4, 5, 6, 7]])

In [9]:
np.array([[1,2,3,4,5],[3,4,5,6,7]])

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])